# Generated by Django 3.2.7 on 2021-10-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idTipoDoc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField()),
                ('activo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('idVolumen', models.AutoField(primary_key=True, serialize=False)),
                ('volumen', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('fecha_alta', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.IntegerField()),
                ('pagina_final', models.IntegerField()),
                ('transcripcion', models.TextField()),
                ('lugar', models.CharField(max_length=200)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.tipodocumento')),
                ('volumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.volumen')),
            ],
        ),
    ]
