# Generated by Django 3.2.7 on 2021-11-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.perfil'),
            preserve_default=False,
        ),
    ]
