# Generated by Django 3.2.7 on 2021-11-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20211107_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='mofificado',
            new_name='modificado',
        ),
    ]
