# Generated by Django 3.2.7 on 2021-11-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_rename_mofificado_registro_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='modificado_fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
