# Generated by Django 3.2.7 on 2021-11-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_registro_modificado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumen',
            name='descripcion',
            field=models.TextField(default='descripcion'),
            preserve_default=False,
        ),
    ]
