# Generated by Django 3.2.7 on 2021-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_volumen_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='volumen',
            field=models.IntegerField(),
        ),
    ]
