# Generated by Django 3.2.9 on 2021-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_alter_volumen_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='relacionado',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
