# Generated by Django 3.2.9 on 2021-11-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_registro_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='relacionado',
            field=models.TextField(blank=True),
        ),
    ]
