# Generated by Django 3.2.7 on 2021-10-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registro', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('idcoleccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('privada', models.IntegerField(default=1)),
                ('activa', models.IntegerField(default=1)),
                ('legislacion', models.ManyToManyField(to='Registro.Registro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInscrito',
            fields=[
                ('idUsuarioInscrito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coleccion.coleccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.perfil')),
            ],
        ),
    ]
