# Generated by Django 3.2.7 on 2021-11-12 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Coleccion', '0003_coleccion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='fecha_modificacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coleccion',
            name='modificado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coleccion_requests_modified', to='Usuario.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccion_requests_created', to='Usuario.perfil'),
        ),
    ]
