# Generated by Django 3.2.9 on 2021-11-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_alter_registro_relacionado'),
        ('Coleccion', '0004_auto_20211112_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='registro',
            field=models.ManyToManyField(blank=True, to='Registro.Registro'),
        ),
    ]
